<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Minicon.SimpleAdmin.Tests</RootNamespace>
    <AssemblyName>Minicon.SimpleAdmin.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.8" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="System.IO.Abstractions" Version="22.1.1" />
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" Version="22.1.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Minicon.SimpleAdmin.Shared/Minicon.SimpleAdmin.Shared.csproj" />
    <ProjectReference Include="../Minicon.SimpleAdmin.Services/Minicon.SimpleAdmin.Services.csproj" />
    <ProjectReference Include="../Minicon.SimpleAdmin.Checkers/Minicon.SimpleAdmin.Checkers.csproj" />
    <ProjectReference Include="../Minicon.SimpleAdmin.HtmlGenerator/Minicon.SimpleAdmin.HtmlGenerator.csproj" />
    <ProjectReference Include="../Minicon.SimpleAdmin.Worker/Minicon.SimpleAdmin.Worker.csproj" />
    <ProjectReference Include="../Minicon.SimpleAdmin.WebUI/Minicon.SimpleAdmin.WebUI.csproj" />
  </ItemGroup>

</Project>
